global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'abc-api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    
  - job_name: 'abc-models'
    static_configs:
      - targets: ['model-server:8080']
    metrics_path: '/metrics'

